# Generated by Django 5.0.6 on 2024-07-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=20, null=True)),
                ('height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True)),
                ('permanent_house_no', models.CharField(blank=True, max_length=10, null=True)),
                ('permanent_street', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_subd', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_brgy', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_city', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_province', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('father_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('father_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name_ext', models.CharField(blank=True, max_length=10, null=True)),
                ('mother_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_middle_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
